services:
  backend:
    container_name: books-backend
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: .env
    restart: always
    networks:
      - backend
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080

  mongo:
    image: mongo:6.0.14
    container_name: mongo
    env_file: .env
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - mongo_data:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    networks:
      - backend

  mongo-express-python:
    image: mongo-express:1-20
    container_name: mongodb-express-python
    depends_on:
      - mongo
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASS}
      - ME_CONFIG_BASICAUTH_USERNAME=${EXPRESS_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${EXPRESS_PASS}
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    name: backend
